#!/bin/bash
# 航点和任务管理快捷命令

echo "======================================"
echo "🗺️  航点管理快捷命令"
echo "======================================"
echo ""
echo "📌 保存当前位置为航点:"
echo "   ros2 topic pub -1 /waypoint/name std_msgs/msg/String \"{data: 'point1'}\""
echo "   ros2 service call /waypoint/save std_srvs/srv/Trigger"
echo ""
echo "📋 列出所有航点:"
echo "   ros2 service call /waypoint/list std_srvs/srv/Trigger"
echo ""
echo "🚀 前往指定航点:"
echo "   ros2 topic pub -1 /waypoint/name std_msgs/msg/String \"{data: 'point1'}\""
echo "   ros2 service call /waypoint/goto std_srvs/srv/Trigger"
echo ""
echo "🗑️  删除航点:"
echo "   ros2 topic pub -1 /waypoint/name std_msgs/msg/String \"{data: 'point1'}\""
echo "   ros2 service call /waypoint/delete std_srvs/srv/Trigger"
echo ""
echo "======================================"
echo "🤖 任务管理快捷命令"
echo "======================================"
echo ""
echo "📋 列出所有任务:"
echo "   ros2 service call /mission/list std_srvs/srv/Trigger"
echo ""
echo "▶️  执行任务:"
echo "   ros2 topic pub -1 /mission/name std_msgs/msg/String \"{data: 'patrol_route'}\""
echo "   ros2 service call /mission/execute std_srvs/srv/Trigger"
echo ""
echo "⏸️  暂停任务:"
echo "   ros2 service call /mission/pause std_srvs/srv/SetBool \"{data: true}\""
echo ""
echo "▶️  继续任务:"
echo "   ros2 service call /mission/pause std_srvs/srv/SetBool \"{data: false}\""
echo ""
echo "⛔ 停止任务:"
echo "   ros2 service call /mission/stop std_srvs/srv/Trigger"
echo ""
echo "======================================"
echo "📊 监控话题"
echo "======================================"
echo ""
echo "查看航点标记:"
echo "   ros2 topic echo /waypoint_markers"
echo ""
echo "查看任务状态:"
echo "   ros2 topic echo /mission/status"
echo ""
echo "======================================"
